account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.news, name='news'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('i_follow/', views.i_follow, name='i_follow'),
    path('edit_mypage/', views.edit_mypage, name='edit_mypage'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('confirm_delete_profile/', views.confirm_delete_profile, name='confirm_delete_profile'),
]

artnet/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('styles/', views.styles, name='styles'),
    path('styles/<str:style>/', views.image_list, name='list_style'),
    path('edit_painting/<int:painting_id>/', views.edit_painting, name='edit_painting'),
    path('deactivate_painting/<int:painting_id>/', views.deactivate_painting, name='deactivate_painting'),
    path('activate_painting/<int:painting_id>/', views.activate_painting, name='activate_painting'),
    path('delete_painting/<int:painting_id>/', views.delete_painting, name='delete_painting'),
    path('confirm_delete_painting/<int:painting_id>/', views.confirm_delete_painting, name='confirm_delete_painting'),
    path('all_comments/<int:painting_id>/', views.all_comments, name='all_comments'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    about = models.TextField(blank=True)
    activity = models.BooleanField(default=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User',
                                  related_name='rel_from_set',
                                  on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User',
                                related_name='rel_to_set',
                                on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'


user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField('self',
                                                through=Contact,
                                                related_name='followers',
                                                symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

    

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo', 'about')

account/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from actions.utils import create_action, delete_action
from actions.models import Action
from .models import Profile, Contact
from .forms import UserRegistrationForm, \
                   UserEditForm, ProfileEditForm
from images.models import Image


@login_required
def news(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id',
                                                       flat=True)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related('user', 'user__profile')\
                     .prefetch_related('target')[:10]

    return render(request,
                  'account/news.html',
                  {'section': 'News',
                   'actions': actions})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})



@login_required
def user_list(request):
    users = User.objects.filter(is_active=True).exclude(id=1).order_by('username')
    return render(request,
                  'account/user/list.html',
                  {'section': 'Artists',
                   'users': users})

@login_required
def user_detail(request, username):
    user = get_object_or_404(User,
                             username=username,
                             is_active=True)
    images = Image.objects.filter(activity='Active', user=user)
    not_active_images = Image.objects.filter(activity='Inactive', user=user)
    return render(request,
                  'account/user/detail.html',
                  {'section': 'Artists',
                   'user': user, 'images': images, 'not_active_images': not_active_images})


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user,
                                              user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'error'})
    return JsonResponse({'status':'error'})


@login_required
def i_follow(request):
    users = request.user.following.all()
    return render(request,
                  'account/user/list.html',
                  {'section': 'Artists',
                   'users': users})


@login_required
def edit_mypage(request):
    paintings = Image.objects.filter(activity='Active', user=request.user)    
    return render(request,
                  'account/edit_mypage.html',
                  {'paintings': paintings})


@login_required
def confirm_delete_profile(request):
    return render(request, 'account/confirm_delete_profile.html')

@login_required
def delete_profile(request):
    images = Image.objects.filter(user=request.user)
    Contact.objects.filter(user_to=request.user).delete()
    for image in images:
        delete_action(image)
    delete_action(request.user)
    get_object_or_404(User, id=request.user.id).delete()
    messages.success(request, 'Profile deleted successfully')
    return HttpResponseRedirect(reverse("login"))

account/templates/base.html
{% load images_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #87cefa;">
    <span class="navbar-brand" style="color: blue; font-size:36px;" >The Artists Network</span>                      
	  {% if request.user.is_authenticated %}
	    <ul class="navbar-nav mr-auto">                                
		  <li class="nav-item">
			<a class="nav-link" style="color: blue" href="{% url 'news' %}">New Activities</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" style="color: blue" href="{% url 'images:list' %}">Paintings</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" style="color: blue" href="{% url 'user_list' %}">Artists</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" style="color: blue" href="{{ request.user.get_absolute_url }}">My Page</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" style="color: blue" href="{% url 'images:styles' %}">Styles</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" style="color: blue" href="{% url 'i_follow' %}">Artists I follow</a>
		  </li>
	    </ul>
	    <ul class="navbar-nav ml-auto">										
		  <li class="nav-item">
		    <a class="nav-link" style="color: blue" href="#">Hello, {{ request.user.first_name }}!</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" style="color: blue" href="{% url 'logout' %}">Log Out</a>
		  </li>					
	    </ul>
	  
	  {% endif %}           
  </nav>


  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}



  <div class="row">
    {% if request.user.is_authenticated %}
	  <div class="sidebar2 col-lg-3 col-md-4 col-sm-4 col-xs-4">
	    <h5>Latest Paintings:</h5>
		{% show_latest_paintings 3 %}
		<h5>Most popular Paintings:</h5>
		{% show_most_liked_paintings 3 %}
		
		<h5>
		You can <a href="{% url "edit" %}">edit your profile</a>
		or <a href="{% url "password_change" %}">change your password</a>.
		</h5>
		
	  </div>
	  <div class="content col-lg-9 col-md-8 col-sm-8 col-xs-8">
    {% else %}
	  <div class="sidebar1 col-lg-1 col-md-1 col-sm-1 col-xs-1">
	  </div>
	  <div class="content col-lg-11 col-md-11 col-sm-11 col-xs-11">
	{% endif %}
	  {% block content %}{% endblock %}
	  </div>
  </div>
	

 

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>

</body>
</html>