artnet/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('styles/', views.styles, name='styles'),
    path('styles/<str:style>/', views.image_list, name='list_style'),
    path('edit_painting/<int:painting_id>/', views.edit_painting, name='edit_painting'),
    path('deactivate_painting/<int:painting_id>/', views.deactivate_painting, name='deactivate_painting'),
    path('activate_painting/<int:painting_id>/', views.activate_painting, name='activate_painting'),
    path('delete_painting/<int:painting_id>/', views.delete_painting, name='delete_painting'),
    path('confirm_delete_painting/<int:painting_id>/', views.confirm_delete_painting, name='confirm_delete_painting'),
    path('all_comments/<int:painting_id>/', views.all_comments, name='all_comments'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    STATUS_CHOICES = (('Renaissance', 'Renaissance'),
                      ('Mannerism', 'Mannerism'),
                      ('Baroque', 'Baroque'),
                      ('Classicism', 'Classicism'),
                      ('Romanticism', 'Romanticism'),
                      ('Impressionism', 'Impressionism'),
                      ('Expressionism', 'Expressionism'),
                      ('Avant-garde', 'Avant-garde'),
                      ('Other', 'Other'))
    ACTIVITY_CHOICES = (('Active', 'Active'),
                      ('Inactive', 'Inactive'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            blank=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(db_index=True,
                                              default=0)
    style = models.CharField(max_length=200, choices=STATUS_CHOICES,
                              default='Other')
    activity = models.CharField(max_length=200, choices=ACTIVITY_CHOICES,
                              default='Active')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])



class Comment(models.Model):
    image = models.ForeignKey(Image,
                             on_delete=models.CASCADE,
                             related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='comment_created',
                             on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.user} on {self.image}'

images/forms.py
from django import forms
from .models import Image
from .models import Comment


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'image', 'description', 'style')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, \
                                  PageNotAnInteger
from common.decorators import ajax_required
from actions.utils import create_action, delete_action
from .forms import ImageCreateForm, CommentForm
from .models import Image, Comment


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'loaded new painting', new_item)
            messages.success(request, 'Image added successfully')

            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)

    return render(request,
                  'images/image/create.html',
                  {'section': 'Paintings',
                   'form': form})
@login_required
def image_detail(request, id, slug):
    image = get_object_or_404(Image, activity='Active', id=id, slug=slug)
    comments = image.comments.all()[:3]
    new_comment = None
    if request.method == 'GET':
        comment_form = CommentForm()        
    else:
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.image = image
            new_comment.user = request.user
            new_comment.save()
            create_action(request.user, 'loaded new comment to', image)
    return render(request,
                      'images/image/detail.html',
                      {'section': 'Paintings',
                      'image': image,
                      'comment_form': comment_form,
                      'comments': comments,
                      'new_comment': new_comment,})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(activity='Active', id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                image.total_likes = image.total_likes + 1
                image.save()
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
                image.total_likes = image.total_likes - 1
                image.save()
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})


@login_required
def image_list(request, style=None):
    if style:
        images = Image.objects.filter(activity='Active', style=style).order_by('-total_likes')
    else:
        images = Image.objects.filter(activity='Active').order_by('-total_likes')
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'Paintings', 'images': images, 'style':style})
    return render(request,
                  'images/image/list.html',
                   {'section': 'Paintings', 'images': images, 'style':style})


@login_required
def styles(request):
    styles = ['Renaissance', 'Mannerism', 'Baroque', 'Classicism',
                      'Romanticism', 'Impressionism', 'Expressionism',
                      'Avant-garde', 'Other']
    return render(request,
                  'images/image/styles.html',
                   {'section': 'Styles', 'styles': styles})


@login_required
def edit_painting(request, painting_id):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'reloaded painting', new_item)
            messages.success(request, 'Image changed successfully')
            return redirect(new_item.get_absolute_url())
        else:
            messages.error(request, 'Error updating your painting')
    else:
        image = get_object_or_404(Image, activity='Active', id=painting_id)
        form = ImageCreateForm(instance=image)
    return render(request,
                  'images/image/edit_painting.html',
                  {'form': form, 'painting_id': painting_id})

@login_required
def deactivate_painting(request, painting_id):
    image = get_object_or_404(Image, activity='Active', id=painting_id)
    image.activity = 'Inactive'
    image.save()
    images = Image.objects.filter(activity='Active', user=request.user)
    not_active_images = Image.objects.filter(activity='Inactive', user=request.user)
    delete_action(image)
    messages.success(request, 'Image deactivated successfully')
    return render(request,
                  'account/user/detail.html',
                  {'section': 'Artists',
                   'user': request.user, 'images': images, 'not_active_images': not_active_images})

@login_required
def activate_painting(request, painting_id):
    image = get_object_or_404(Image, activity='Inactive', id=painting_id)
    image.activity = 'Active'
    image.save()
    images = Image.objects.filter(activity='Active', user=request.user)
    not_active_images = Image.objects.filter(activity='Inactive', user=request.user)
    messages.success(request, 'Image activated successfully')
    return render(request,
                  'account/user/detail.html',
                  {'section': 'Artists',
                   'user': request.user, 'images': images, 'not_active_images': not_active_images})


@login_required
def confirm_delete_painting(request, painting_id):
    image = get_object_or_404(Image, id=painting_id)
    return render(request, 'images/image/confirm_delete_painting.html',
                  {'image': image})

@login_required
def delete_painting(request, painting_id):
    image = get_object_or_404(Image, id=painting_id)
    delete_action(image)
    image.delete()
    images = Image.objects.filter(activity='Active', user=request.user)
    not_active_images = Image.objects.filter(activity='Inactive', user=request.user)
    messages.success(request, 'Image deleted successfully')
    return render(request,
                  'account/user/detail.html',
                  {'section': 'Artists',
                   'user': request.user, 'images': images, 'not_active_images': not_active_images})


@login_required    
def all_comments(request, painting_id):
    image = get_object_or_404(Image, activity='Active', id=painting_id)
    comments = image.comments.all()
    return render(request,
                  'images/image/comments.html',
                  {'comments': comments,
                   'image': image})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    images = Image.objects.filter(activity='Active', user=request.user)
    not_active_images = Image.objects.filter(activity='Inactive', user=request.user)
    messages.success(request, 'Comment deleted successfully')
    return render(request,
                  'account/user/detail.html',
                  {'section': 'Artists',
                   'user': request.user, 'images': images, 'not_active_images': not_active_images})

images/templates/images/image/comments.html
{% extends "base.html" %}

{% block title %}All Comments{% endblock %}

{% block content %}
  <h1>All Comments to {{image.title}}</h1>
  



  
    
  <div>
	{% with comments.count as total_comments %}
		<h4>{{ total_comments }} comment{{ total_comments|pluralize }}</h4>
	{% endwith %}
	
	{% for comment in comments %}
		<div>
			<p>
				Comment {{ forloop.counter }} by <a href="{{ comment.user.get_absolute_url }}">{{ comment.user.get_full_name }}</a>
				{{ comment.created }}{% if image.user == request.user %} (<a href="{% url 'images:delete_comment' comment_id %}">delete</a> this comment){% endif %}:
			</p>
           {{ comment.body|linebreaks }}
		</div>
	{% endfor %}	
	
   </div>
{% endblock %}

images/templates/images/image/confirm_delete_painting.html
{% extends "base.html" %}

{% block title %}Confirmation of deletion of Painting.{% endblock %}

{% block content %}
  <h1>Are you sure you want to delete the Painting?</h1>
  <ul>
    <li><a href="{% url 'images:delete_painting' image.id %}">Yes</a></li>
    <li><a href="{% url 'images:detail' image.id image.slug %}">No</a></li>
  </ul>  

{% endblock %}

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Download your Painting{% endblock %}

{% block content %}
  <h1>Download your Painting</h1>
  <form action="." method="post" enctype="multipart/form-data" >
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Download it!">
  </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  <h5>Artist: <a href="{{ user.get_absolute_url }}">{{ image.user.get_full_name }}</a></h5>
  <h5>Style: <a href="{% url 'images:list_style' image.style %}">{{ image.style }}</a></h5>


<div class="row">
<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
  {% load thumbnail %}
    <a href="{{ image.image.url }}">
      <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
    </a>
</div>
<div class="col-lg-7 col-md-7 col-sm-7 col-xs-0">	
	{{ image.description|linebreaks }}
</div>	
</div>

	
<div>
{% with total_likes=image.total_likes users_like=image.users_like.all %}
    <span class="count">
	  <span  class="total">{{ total_likes }}</span>
	  like{{ total_likes|pluralize }}
	</span>
	{% if image.user.get_full_name != request.user.get_full_name %}
	<a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
	  {% if request.user not in users_like %}
		Like
	  {% else %}
		Unlike
	  {% endif %}
	</a>
	{% endif %}
{% endwith %}
</div>


		
<div>
{% with users_like=image.users_like.all %}
  <div class="image-likes">
    {% for user in users_like %}
      <div>
		<p><a href="{{ user.get_absolute_url }}">{{ user.get_full_name }}</a> liked the Painting</p>	
      </div>
    {% empty %}
      Nobody likes this image yet.
    {% endfor %}
  </div>
{% endwith %}
</div>
  
    
<div>
	{% with comments.count as total_comments %}
	{% if total_comments %}
		<h4>The first {{ total_comments }} comment{{ total_comments|pluralize }}</h4>
	
	{% for comment in comments %}
		<div>
			<p>
				Comment {{ forloop.counter }} by <a href="{{ comment.user.get_absolute_url }}">{{ comment.user.get_full_name }}</a>
				{{ comment.created }}{% if image.user == request.user %} (<a href="{% url 'images:delete_comment' comment.id %}">delete</a> this comment){% endif %}:
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% endfor %}
	{% else %}
		<p>There are no comments yet.</p>
	{% endif %}
	
	{% if total_comments == 3 %}
	<h4><a href="{% url 'images:all_comments' image.id %}">See all Comments</a></h4>
	{% endif %}
	{% endwith %}
	
	{% if image.user.get_full_name != request.user.get_full_name %}
	  {% if new_comment %}
		<h2>Your comment has been added.</h2>
	  {% else %}
	    <h3>Add a new comment</h3>
		<form action="." method="post">
		  {{ comment_form.as_p }}
		  {% csrf_token %}
		  <p><input type="submit" value="Add comment"></p>
		</form>
	  {% endif %}
	{% endif %}	
</div>
{% endblock %}


{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok') {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action',
            previous_action == 'like' ? 'unlike' : 'like');
          // toggle link text
          $('a.like').text(
            previous_action == 'like' ? 'Unlike' : 'Like');

          // update total likes
          var previous_likes = parseInt(
            $('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

images/templates/images/image/edit_painting.html
{% extends "base.html" %}

{% block title %}Edit Painting{% endblock %}

{% block content %}
  <h1>Deactivate Painting</h1>
    <a href="{% url 'images:deactivate_painting' painting_id %}">Deactivate</a>
  <h1>Delete Painting</h1>
    <a href="{% url 'images:confirm_delete_painting' painting_id %}">Delete</a>
  <h1>Edit Painting</h1>
	<form action="." method="post" enctype="multipart/form-data" >
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Load">
    </form>

{% endblock %}

images/templates/images/image/latest_paintings.html
<ul>
{% for painting in latest_paintings %}
  <li>
    <a href="{{ painting.get_absolute_url }}">{{ painting.title }}</a>
  </li>
{% endfor %}
</ul>

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}All Paintings{% endblock %}

{% block content %}
{% if style %}
  <h1>{{style}} ({{images|length}})</h1>
{% else %}
  <h1>All Paintings ({{images|length}})</h1>
{% endif %}  
  <div id="image-list">
    {% include "images/image/list_ajax.html" %}
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false &&
    block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

<div class="container">		
	<div class="card-deck">
		{% for image in images %}
		<div style="padding: 12px;">		
			<div class="card" style="width: 300;">
				<a href="{{ image.get_absolute_url }}">
					{% thumbnail image.image 300x300 crop="smart" as im %}
					<a href="{{ image.get_absolute_url }}">
						<img src="{{ im.url }}">
					</a>
				</a>
				<div class="card-body">
					<h5 class="card-title"><span style="font-weight: bold;">{{ image.title }}</span></h5>
					<p class="card-text">By: <a href="{{ image.user.get_absolute_url }}">{{ image.user.get_full_name }}</a></p>
					<a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
				</div>
			</div>			
		</div>		
		{% endfor %}
	</div>				
</div>

images/templates/images/image/most_liked_paintings.html
<ul>
{% for painting in most_liked_paintings %}
  <li>
    <a href="{{ painting.get_absolute_url }}">{{ painting.title }}</a>
  </li>
{% endfor %}
</ul>

images/templates/images/image/styles.html
{% extends "base.html" %}

{% block title %}Styles{% endblock %}

{% block content %}
  <h1>Styles</h1>

  <ul>
	{% for style in styles %}
		<li><a href="{% url 'images:list_style' style %}">{{ style }}</a></li>
	{% endfor %}
  </ul>

{% endblock %}